co = coroutine.create(function (a,b)
   print("before yield")
   coroutine.yield(a + b, a - b)
   print("after yield")
end)
local ret,a,b = coroutine.resume(co, 20, 10)
print(ret, a, b)
ret,a,b = coroutine.resume(co)
print(ret, a, b)
